# Site settings
title: digitalcyb.org
email: me@amansoni.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://digitalcyb.org" # the base hostname & protocol for your site

twitter_username: amansoni
github_username: amansoni

# Build settings
markdown: kramdown

# Staticman
staticman:
 allowedFields: ['address', 'name', 'title', 'description', 'rating']
 branch: gh-pages
 commitMessage: "Hey human, here is a new entry."
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "_data/reviews"
requiredFields: ['name', 'title', 'description', 'rating']
